import Link from "next/link";
import { advanceToSignatureAction, reviewDocumentAction, saveFinancialReviewAction } from "@/app/actions/enrollment-review";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { EnrollmentBundle } from "@/features/students/types";
import { DUE_DAY_OPTIONS, beltForGub, type GubOption } from "@/features/students/options";
import { ROUTES } from "@/lib/navigation/routes";
import { renewContractAction } from "@/app/actions/renewals";

const dateValue = (value?: string | null) => value?.slice(0, 10) ?? "";
const documentLabel = { profile_photo: "Foto do aluno", medical_certificate: "Atestado médico" } as const;

export function ReviewPanel({ bundle, reviews, notice }: { bundle: EnrollmentBundle; reviews: Array<Record<string, unknown>>; notice?: string }) {
  const { student, enrollment, documents } = bundle;
  const currentBelt = student.gub ? beltForGub(student.gub as GubOption) : student.current_belt;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={ROUTES.adminEnrollments} className="text-sm text-muted-foreground underline">Voltar para alunos</Link><h1 className="mt-2 text-2xl font-semibold">{student.full_name}</h1><p className="text-muted-foreground">CPF {student.cpf ?? "não informado"} · Faixa {currentBelt ?? "não informada"}</p></div><Badge variant="outline">{enrollment.status.replaceAll("_", " ")}</Badge></div>
    {notice ? <p className="rounded-lg bg-muted p-3 text-sm">{notice}</p> : null}
    <div className="grid gap-5 lg:grid-cols-2">
      <Card><CardHeader><CardTitle>Ficha do aluno</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm">
        <p><strong>Nascimento:</strong> {dateValue(student.birth_date) || "—"}</p><p><strong>WhatsApp:</strong> {student.whatsapp || "—"}</p><p><strong>Endereço:</strong> {student.address || "—"}</p><p><strong>Contato de emergência:</strong> {student.emergency_contact_name || "—"} · {student.emergency_contact_phone || "—"}</p><p><strong>Início no TKD:</strong> {dateValue(student.started_at_tkd) || "—"} · GUB {student.gub ?? "—"}</p><p><strong>Turma:</strong> {student.training_class || "—"}</p>
      </CardContent></Card>
      <Card><CardHeader><CardTitle>Informações de saúde</CardTitle><CardDescription>Acesso restrito à administração.</CardDescription></CardHeader><CardContent className="grid gap-2 text-sm"><p><strong>Condição:</strong> {student.health_condition === "yes" ? "Sim" : student.health_condition === "no" ? "Não" : "—"}</p><p><strong>Detalhes:</strong> {student.health_details || "—"}</p><p><strong>Medicamentos:</strong> {student.medications || "—"}</p><p><strong>Alergias:</strong> {student.allergies || "—"}</p><p><strong>Lesões:</strong> {student.injuries || "—"}</p></CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>Documentos</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">
      {documents.length === 0 ? <p className="text-sm text-muted-foreground">Nenhum documento enviado.</p> : documents.map((document) => <div key={document.$id} className="space-y-3 rounded-lg border p-4"><div className="flex items-center justify-between gap-2"><Link className="font-medium underline" href={`/api/student-documents/${document.$id}`}>{documentLabel[document.document_type]}</Link><Badge variant="outline">{document.status}</Badge></div><form action={reviewDocumentAction} className="space-y-2"><input type="hidden" name="student_id" value={student.$id} /><input type="hidden" name="document_id" value={document.$id} /><Input name="reason" placeholder="Motivo, obrigatório ao reprovar" /><div className="flex gap-2"><Button name="decision" value="approved" type="submit">Aprovar</Button><Button name="decision" value="rejected" type="submit" variant="destructive">Reprovar</Button></div></form></div>)}
    </CardContent></Card>
    <Card><CardHeader><CardTitle>Condições financeiras e contrato</CardTitle><CardDescription>Valores em centavos para evitar arredondamentos (ex.: 15000 = R$ 150,00).</CardDescription></CardHeader><CardContent><form action={saveFinancialReviewAction} className="grid gap-4 md:grid-cols-3"><input type="hidden" name="student_id" value={student.$id} /><label className="grid gap-2"><span className="text-sm font-medium">Mensalidade (centavos)</span><Input name="monthly_fee_cents" type="number" min="0" defaultValue={enrollment.monthly_fee_cents ?? ""} required /></label><label className="grid gap-2"><span className="text-sm font-medium">Desconto (centavos)</span><Input name="discount_cents" type="number" min="0" defaultValue={enrollment.discount_cents ?? 0} /></label><label className="grid gap-2"><span className="text-sm font-medium">Vencimento aprovado</span><select name="approved_due_day" defaultValue={enrollment.approved_due_day ?? enrollment.requested_due_day ?? ""} required className="h-8 rounded-lg border bg-background px-2.5 text-sm"><option value="">Selecione o dia</option>{DUE_DAY_OPTIONS.map((day) => <option key={day} value={day}>Dia {day}</option>)}</select></label><label className="grid gap-2"><span className="text-sm font-medium">Primeiro vencimento</span><Input name="first_due_date" type="date" defaultValue={dateValue(enrollment.first_due_date)} required /></label><label className="grid gap-2"><span className="text-sm font-medium">Início do contrato</span><Input name="contract_start" type="date" defaultValue={dateValue(enrollment.contract_start)} required /></label><label className="grid gap-2"><span className="text-sm font-medium">Fim do contrato</span><Input name="contract_end" type="date" defaultValue={dateValue(enrollment.contract_end)} required /></label><Button type="submit" className="md:col-span-3 md:w-fit">Salvar condições</Button></form></CardContent></Card>
    {enrollment.status === "awaiting_renewal" ? <Card><CardHeader><CardTitle>Renovar contrato</CardTitle><CardDescription>Uma nova versão será emitida; o contrato anterior continuará preservado.</CardDescription></CardHeader><CardContent><form action={renewContractAction} className="flex flex-wrap items-end gap-3"><input type="hidden" name="student_id" value={student.$id} /><label className="grid gap-2"><span className="text-sm font-medium">Nova data final</span><Input name="ends_at" type="date" required /></label><Button type="submit">Emitir renovação</Button></form></CardContent></Card> : <Card><CardHeader><CardTitle>Concluir análise</CardTitle><CardDescription>A assinatura só é liberada com ficha completa, dois documentos aprovados, modelo publicado e condições financeiras confirmadas.</CardDescription></CardHeader><CardContent><form action={advanceToSignatureAction}><input type="hidden" name="student_id" value={student.$id} /><Button type="submit">Liberar para assinatura</Button></form></CardContent></Card>}
    <Card><CardHeader><CardTitle>Histórico da análise</CardTitle></CardHeader><CardContent className="space-y-3">{reviews.length === 0 ? <p className="text-sm text-muted-foreground">Nenhuma análise registrada.</p> : reviews.map((review) => <div key={String(review.$id)} className="border-l-2 pl-3 text-sm"><p className="font-medium">{String(review.action).replaceAll("_", " ")}</p><p className="text-muted-foreground">{new Date(String(review.created_at)).toLocaleString("pt-BR")}{review.notes ? ` · ${String(review.notes)}` : ""}</p></div>)}</CardContent></Card>
  </div>;
}
