import Link from "next/link";
import { advanceToSignatureAction, reviewDocumentAction, saveFinancialReviewAction } from "@/app/actions/enrollment-review";
import { FeedbackAlert } from "@/components/shared/feedback-alert";
import { FormSubmitButton } from "@/components/shared/form-submit-button";
import { StatusBadge } from "@/components/shared/status-badge";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { EnrollmentBundle } from "@/features/students/types";
import { DUE_DAY_OPTIONS, beltForGub, type GubOption } from "@/features/students/options";
import { ROUTES } from "@/lib/navigation/routes";
import { renewContractAction } from "@/app/actions/renewals";

const dateValue = (value?: string | null) => value?.slice(0, 10) ?? "";
const documentLabel = { profile_photo: "Foto do aluno", medical_certificate: "Atestado médico" } as const;

export function ReviewPanel({ bundle, reviews, notice }: { bundle: EnrollmentBundle; reviews: Array<Record<string, unknown>>; notice?: string }) {
  const { student, enrollment, documents } = bundle;
  const currentBelt = student.gub ? beltForGub(student.gub as GubOption) : student.current_belt;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={ROUTES.adminEnrollments} className="text-sm text-muted-foreground underline">Voltar para alunos</Link><h1 className="mt-2 text-2xl font-semibold">{student.full_name}</h1><p className="text-muted-foreground">CPF {student.cpf ?? "não informado"} · Faixa {currentBelt ?? "não informada"}</p></div><StatusBadge tone={enrollment.status === "active" ? "success" : enrollment.status === "cancelled" ? "danger" : "info"}>{enrollment.status.replaceAll("_", " ")}</StatusBadge></div>
    {notice ? <FeedbackAlert tone={notice.includes("Não") ? "danger" : "success"} title={notice} /> : null}
    <div className="grid gap-5 lg:grid-cols-2">
      <Card><CardHeader><CardTitle>Ficha do aluno</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm">
        <p><strong>Nascimento:</strong> {dateValue(student.birth_date) || "—"}</p><p><strong>WhatsApp:</strong> {student.whatsapp || "—"}</p><p><strong>Endereço:</strong> {student.address || "—"}</p><p><strong>Contato de emergência:</strong> {student.emergency_contact_name || "—"} · {student.emergency_contact_phone || "—"}</p><p><strong>Início no TKD:</strong> {dateValue(student.started_at_tkd) || "—"} · GUB {student.gub ?? "—"}</p><p><strong>Turma:</strong> {student.training_class || "—"}</p>
      </CardContent></Card>
      <Card><CardHeader><CardTitle>Informações de saúde</CardTitle><CardDescription>Acesso restrito à administração.</CardDescription></CardHeader><CardContent className="grid gap-2 text-sm"><p><strong>Condição:</strong> {student.health_condition === "yes" ? "Sim" : student.health_condition === "no" ? "Não" : "—"}</p><p><strong>Detalhes:</strong> {student.health_details || "—"}</p><p><strong>Medicamentos:</strong> {student.medications || "—"}</p><p><strong>Alergias:</strong> {student.allergies || "—"}</p><p><strong>Lesões:</strong> {student.injuries || "—"}</p></CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>Documentos</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">
      {documents.length === 0 ? <p className="text-sm text-muted-foreground">Nenhum documento enviado.</p> : documents.map((document) => <div key={document.$id} className="space-y-3 rounded-lg border p-4"><div className="flex items-center justify-between gap-2"><Link className="font-medium underline" href={`/api/student-documents/${document.$id}`}>{documentLabel[document.document_type]}</Link><StatusBadge tone={document.status === "approved" ? "success" : document.status === "rejected" ? "danger" : "warning"}>{document.status}</StatusBadge></div><div className="flex gap-2"><form action={reviewDocumentAction}><input type="hidden" name="student_id" value={student.$id} /><input type="hidden" name="document_id" value={document.$id} /><input type="hidden" name="decision" value="approved" /><FormSubmitButton pendingLabel="Aprovando…">Aprovar</FormSubmitButton></form><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive">Reprovar</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reprovar {documentLabel[document.document_type]}?</AlertDialogTitle><AlertDialogDescription>Informe o que precisa ser corrigido. O aluno poderá enviar um novo arquivo.</AlertDialogDescription></AlertDialogHeader><form action={reviewDocumentAction} className="space-y-4"><input type="hidden" name="student_id" value={student.$id} /><input type="hidden" name="document_id" value={document.$id} /><input type="hidden" name="decision" value="rejected" /><Field><FieldLabel htmlFor={`document-reason-${document.$id}`}>Motivo da reprovação</FieldLabel><Input id={`document-reason-${document.$id}`} name="reason" required /></Field><AlertDialogFooter><AlertDialogCancel type="button">Cancelar</AlertDialogCancel><AlertDialogAction type="submit" variant="destructive">Confirmar reprovação</AlertDialogAction></AlertDialogFooter></form></AlertDialogContent></AlertDialog></div></div>)}
    </CardContent></Card>
    <Card><CardHeader><CardTitle>Condições financeiras e contrato</CardTitle><CardDescription>Valores em centavos para evitar arredondamentos (ex.: 15000 = R$ 150,00).</CardDescription></CardHeader><CardContent><form action={saveFinancialReviewAction} className="grid gap-4 md:grid-cols-3"><input type="hidden" name="student_id" value={student.$id} /><Field><FieldLabel htmlFor="review-monthly-fee">Mensalidade (centavos)</FieldLabel><Input id="review-monthly-fee" name="monthly_fee_cents" type="number" min="0" defaultValue={enrollment.monthly_fee_cents ?? ""} required /></Field><Field><FieldLabel htmlFor="review-discount">Desconto (centavos)</FieldLabel><Input id="review-discount" name="discount_cents" type="number" min="0" defaultValue={enrollment.discount_cents ?? 0} /></Field><Field><FieldLabel htmlFor="review-due-day">Vencimento aprovado</FieldLabel><Select name="approved_due_day" defaultValue={String(enrollment.approved_due_day ?? enrollment.requested_due_day ?? "")} required><SelectTrigger id="review-due-day" className="w-full"><SelectValue placeholder="Selecione o dia" /></SelectTrigger><SelectContent>{DUE_DAY_OPTIONS.map((day) => <SelectItem key={day} value={String(day)}>Dia {day}</SelectItem>)}</SelectContent></Select></Field><Field><FieldLabel htmlFor="review-first-due">Primeiro vencimento</FieldLabel><Input id="review-first-due" name="first_due_date" type="date" defaultValue={dateValue(enrollment.first_due_date)} required /></Field><Field><FieldLabel htmlFor="review-contract-start">Início do contrato</FieldLabel><Input id="review-contract-start" name="contract_start" type="date" defaultValue={dateValue(enrollment.contract_start)} required /></Field><Field><FieldLabel htmlFor="review-contract-end">Fim do contrato</FieldLabel><Input id="review-contract-end" name="contract_end" type="date" defaultValue={dateValue(enrollment.contract_end)} required /></Field><FormSubmitButton className="md:col-span-3 md:w-fit" pendingLabel="Salvando…">Salvar condições</FormSubmitButton></form></CardContent></Card>
    {enrollment.status === "awaiting_renewal" ? <Card><CardHeader><CardTitle>Renovar contrato</CardTitle><CardDescription>Uma nova versão será emitida; o contrato anterior continuará preservado.</CardDescription></CardHeader><CardContent><form action={renewContractAction} className="flex flex-wrap items-end gap-3"><input type="hidden" name="student_id" value={student.$id} /><Field><FieldLabel htmlFor="renewal-end">Nova data final</FieldLabel><Input id="renewal-end" name="ends_at" type="date" required /></Field><FormSubmitButton pendingLabel="Emitindo…">Emitir renovação</FormSubmitButton></form></CardContent></Card> : <Card><CardHeader><CardTitle>Concluir análise</CardTitle><CardDescription>A assinatura só é liberada com ficha completa, dois documentos aprovados, modelo publicado e condições financeiras confirmadas.</CardDescription></CardHeader><CardContent><form action={advanceToSignatureAction}><input type="hidden" name="student_id" value={student.$id} /><FormSubmitButton pendingLabel="Liberando…">Liberar para assinatura</FormSubmitButton></form></CardContent></Card>}
    <Card><CardHeader><CardTitle>Histórico da análise</CardTitle></CardHeader><CardContent className="space-y-3">{reviews.length === 0 ? <p className="text-sm text-muted-foreground">Nenhuma análise registrada.</p> : reviews.map((review) => <div key={String(review.$id)} className="border-l-2 pl-3 text-sm"><p className="font-medium">{String(review.action).replaceAll("_", " ")}</p><p className="text-muted-foreground">{new Date(String(review.created_at)).toLocaleString("pt-BR")}{review.notes ? ` · ${String(review.notes)}` : ""}</p></div>)}</CardContent></Card>
  </div>;
}
